### PR TITLE
input box prototype

### LINKED ISSUE #10: Implement latitude-longitude box
We'd like users to have the option of selecting event position by providing plaintext lat/lon.
This issue is for implementing the text box in the UI for input and a button to submit the request to the API's hazard route implemented by https://github.com/os-climate/physrisk-api/issues/5.
As is with #11, graphed intensity curve(s) from the response should be displayed below the map box.

### PR DESCRIPTION
**Pull request by deepanshu44**
Added a prototype input box.
Fixes #10 

upload

### CODE REVIEW

**Comment by negillett** [comment]
@deepanshu44, to pass the DCO check you'll need to sign the commit (e.g., `git commit -s`).

**Comment by deepanshu44** [comment]
> @deepanshu44, to pass the DCO check you'll need to sign the commit (e.g., `git commit -s`).

@negillett Done

**Comment by deepanshu44** [comment]
@negillett I've pushed some changes and it includes: 
- A new component file   `CoordinatesInput.js`
- I've copy pasted the `newMap.on("click")` logic on the submit button's [onClick](https://github.com/os-climate/physrisk-ui/pull/38/files#diff-176dceac5ba862881ce4083eccade04615d04596564cf2a0f00e82a6eede2d2eR43) handler, as I don't know what should be the right approach.

Waiting for your input.

**Comment by joemoorhouse** [comment]
Hi @deepanshu44,
That behaviour's indeed what we want - thanks! - but as discussed please can we make it more a search box input (i.e. single text entry)? As discussed in the issue, the MUI TextBox is one way to go but in fact the approach in the link that you identified looks like a much better option:
https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder-accept-coordinates/
I suggest we use exactly this if that's ok (I thought that was what you were suggesting actually in which case seems a great idea)? It seems to provide a great-looking search feature built into the map and easy to add the geo-coding.
By the way, I made some changes in the meantime that cause a conflict, but just necessary to use mapRef.current in place of map. 
Some of the changes fix a bug that may cause issue on certain mobile browsers so interesting to see if that resolved the issue you were seeing.
Thanks,
Joe

**Comment by deepanshu44** [comment]
@joemoorhouse I've implemented the geocoding approach as you can see below
<details>
<summary>
Image
</summary>

Screenshot_20220802-153359_Firefox
</details>

Now I think it would be better to remove the first approach for the input box as I believe you favor the geocoding approach and it also looks more user friendly. 

About the mobile issue,  I still have it. 
I think the issue is with the server `npm start`, as the demo link you've attached was correctly displayed.

**Comment by joemoorhouse** [comment]
Thanks... yes looks good! And I agree: please go ahead and remove the first
approach.
Good to hear that sandbox works on your mobile anyway.

**Comment by deepanshu44** [comment]
Hello @joemoorhouse I am getting a bit confused here. Do we really need to add  geocoder on the map?
As the requirement of this issue was to just implement a simple lat/lon search box. But adding geocoder will also let the user to search for places using simple words (eg. Germany). Is that an overkill? 
Thanks

**Comment by joemoorhouse** [comment]
Hi @deepanshu44, no all good! This issue was indeed for lat/lon only but we also want geocoding and this change gives us both, so great. Makes sense as actually harder not to implement together.

**Comment by joemoorhouse** [comment]
By the way, are the indents missing from CoordinatesInput.js (and if so was some Prettier setting?)?

**Review by negillett — APPROVED** [review]

**Comment by deepanshu44** [comment]
Hello @joemoorhouse,  I have pushed some changes.
Everything seems to be working correctly. 
Earlier when I added geocoder, we had two markers (one from the user click and the other from geocoder).
  So in order to resolve this problem, I added `false` to `marker` property in geocoder and attatched "result" event listener to the same.

**Comment by deepanshu44** [comment]
Also thanks @negillett for approving and letting me work on this issue😄.

**Comment by joemoorhouse** [comment]
That's great - thanks! Was going to suggest using the result event but you
got there first :)

**Review by negillett — APPROVED** [review]

**Comment by joemoorhouse** [comment]
Hi @deepanshu44; hi @negillett, sorry just back from holiday and did not notice that this is approved but not merged. @negillett, please feel free to merge changes as well if you are happy by the way! @deepanshu44 thanks again for this (and are you on OS-C Slack actually?)

**Comment by deepanshu44** [comment]
Thanks @joemoorhouse for merging PR. It was my pleasure to volunteer for this awesome project.

**Pull request merged**
